spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8201
spring:
  peofiles: dev
  application:
    name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
---
server: 
  port: 8202
spring:
  peofiles: test
  application:
    name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/
